name: Run Docker Compose

on:
  push:
    branches:
      - main # Executa quando você fizer push na branch main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose
        run: |
          docker-compose down -v --remove-orphans
          docker-compose up -d

      - name: Verify running containers
        run: docker ps
